### ISSUE TITLE
It's the same level but...

### ISSUE THREAD

**Issue by BasicallyTDuy** [swc132994/BD64-VoH_maps#4]
So I caught this in my stream just a few minutes ago
https://youtu.be/X_kF7v81xYc?t=687
That specific part literally traps the player and does nothing else
I know the levels are different from the original D64 but I don't know if this was intended

**Comment by swc132994** [comment]
I have not spotted a problem. When you pick up the super shotgun the platform drops and the stairs with side doors open so you can escape.
https://www.youtube.com/watch?v=yrFc0FHY2-8

**Comment by BasicallyTDuy** [comment]
> I have not spotted a problem. When you pick up the super shotgun the platform drops and the stairs with side doors open so you can escape. https://www.youtube.com/watch?v=yrFc0FHY2-8

Oh that's weird, what I was playing was like the latest version of the map pack too

**Comment by swc132994** [comment]
I wonder what other addons you may have running. It is possible something maybe be interfering with the map ACS scripts.

**Comment by BasicallyTDuy** [comment]
> I wonder what other addons you may have running. It is possible something maybe be interfering with the map ACS scripts.

I think that could have been the Xtra Good addon since I loaded it after the base mod and the maps, I had nothing else loaded other than those three's

**Comment by swc132994** [comment]
I just tested with Xtragoodies, it still seems ok. I noticed some misaligned wall textures which I have just fixed and have made a tweak to map script for that trap to remove a count of dead monsters before opening the door after grabbing the super shotgun. Try it now.

**Comment by BasicallyTDuy** [comment]
I think I figured it out finally, when the imps don't spawn in D6408, the doors don't open, it sorta depended on the difficulty, it works fine in D6408A though

**Comment by swc132994** [comment]
It could be the case. The update I just posted on my last comment should sort this problem out as that condition is removed from both 08 maps.

The map scripts for both 08 variants for this trap were identical so I am not sure why it would work for one map and fail on 08A.

**Comment by BasicallyTDuy** [comment]
The fact that I do script in Decor., sometimes ZScripts, even made a bunch of PRs for some other mods, wish I knew what to do with the maps'

**Comment by swc132994** [comment]
I know what you mean. At first I didn't know about map ACS for a long time. After  playing around with some maps, I got the hang of it. The main thing is giving objects that you want to manipulate (monsters, items, etc) a thing ID tag. Map sectors such as doors would need a tag to open them to scripted actions. I can show you some examples if you like.

Do you reckon we can close this issue now (it should be resolved)?

**Comment by BasicallyTDuy** [comment]
I just completely forgot about this, hold on let me test
Oh god I forgot to mention that it was tested on Be Gentle! difficulty

**Comment by swc132994** [comment]
I have now fixed this issue. It turns out I had fixed it for map 6408A but not D6408 (I probably forgot to save the changes). Anyway, it's all good now.
